blueprints/auth.py
import os

import flask
import requests_oauthlib
from flask import Blueprint

from blueprints.registration import is_registered

auth = Blueprint("auth", __name__, url_prefix="/auth")

oauth_token_url = "https://discordapp.com/api/oauth2/token"
oauth_authorize_url = "https://discordapp.com/api/oauth2/authorize"
oauth_api_base = "https://discordapp.com/api"

print(f"{os.environ.get('FLASK_ENV')=}")
if os.environ.get("FLASK_ENV") == "development":
    os.environ["OAUTHLIB_INSECURE_TRANSPORT"] = "1"
    protocol = "http://"
    print("enable insecure transport")
else:
    protocol = "https://"


@auth.route("/pre_login")
def pre_login():
    return '<a href="/auth/login">Login</a>'


@auth.route("/login")
def login():
    oauth = requests_oauthlib.OAuth2Session(
        flask.current_app.config["OAUTH2"]["client_id"],
        redirect_uri=protocol
        + flask.request.host
        + flask.url_for("auth.oauth_callback"),
        scope=flask.current_app.config["OAUTH2"]["scope"],
    )
    login_url, state = oauth.authorization_url(oauth_authorize_url)
    flask.session["oauth_state"] = state
    return flask.redirect(login_url)


@auth.route("/oauth_callback")
def oauth_callback():
    discord_session = requests_oauthlib.OAuth2Session(
        flask.current_app.config["OAUTH2"]["client_id"],
        redirect_uri=protocol
        + flask.request.host
        + flask.url_for("auth.oauth_callback"),
        state=flask.session["oauth_state"],
        scope=flask.current_app.config["OAUTH2"]["scope"],
    )
    token = discord_session.fetch_token(
        oauth_token_url,
        client_secret=flask.current_app.config["OAUTH2"]["client_secret"],
        authorization_response=flask.request.url,
    )
    flask.session["discord_token"] = token
    data = discord_session.get(oauth_api_base + "/users/@me").json()

    if not is_registered(data["id"]):
        flask.session["register_info"] = data
        return flask.redirect("/registration/pre_register")

    flask.session["user_info"] = data

    return flask.redirect("/")


@auth.route("/logout")
def logout():
    flask.session.pop("user_info")
    return flask.redirect("/")

blueprints/registration.py
import csv
import io
import traceback

import flask
import flask_sqlalchemy
import requests
from flask import Blueprint
from flask.helpers import flash, make_response
from sqlalchemy import exc, inspect
from wtforms import (
    BooleanField,
    Form,
    RadioField,
    StringField,
    ValidationError,
    validators,
)

import util.global_cache as global_cache
from models.user import User

reg = Blueprint("reg", __name__, url_prefix="/registration")


class RegistrationForm(Form):
    server = RadioField(choices=["yes", "no"])
    colonist = StringField(
        validators=[validators.Length(min=3, max=12), validators.InputRequired()]
    )
    country = StringField(
        validators=[validators.Length(min=3, max=80), validators.Optional()]
    )
    email = StringField(
        validators=[
            validators.Length(min=5, max=120),
            validators.Email(),
            validators.Optional(),
        ]
    )
    use_discord = RadioField(choices=["please-help", "no-help"])
    assistance = StringField(
        validators=[validators.Length(min=0, max=500), validators.Optional()]
    )
    ck = BooleanField()
    ck_5_6 = BooleanField()
    sf = BooleanField()
    sf_5_6 = BooleanField()
    cksf = BooleanField()
    cksf_5_6 = BooleanField()
    base_5_6 = BooleanField()
    base_7_8 = BooleanField()

    def validate_server(form, field):
        if field.data != "yes":
            raise ValidationError("You must join the discord to participate")


@reg.before_app_first_request
def setup_db():
    import app

    global_cache.sql_db.init_app(app.app)
    global_cache.sql_db.create_all()


@reg.route("/pre_register")
def pre_register():
    if flask.session.get("register_info"):
        id = int(flask.session["register_info"]["id"])
        if not is_registered(id):
            flask.session["registration_key"] = id
            return flask.redirect(flask.url_for("reg.register", user_id=id))
    return flask.redirect("/")


@reg.route("/register/<int:user_id>", methods=["GET", "POST"])
def register(user_id):
    if flask.session.get("registration_key") == user_id:
        form = RegistrationForm(flask.request.form)
        if (
            flask.request.method == "POST"
            and form.validate()
            and not is_registered(user_id)
        ):
            (res,) = global_cache.sql_db.session.query(
                User.query.filter(User.user_id == user_id).exists()
            ).first()
            if res:
                return update_registration(user_id)

            user = User(
                user_id=user_id,
                username=flask.session["register_info"]["username"]
                + "#"
                + flask.session["register_info"]["discriminator"],
            )
            global_cache.sql_db.session.add(user)
            try:
                user.update_auxiliary_fields(form)
            except exc.SQLAlchemyError:
                traceback.print_exc()
                print("form.errors=", form.errors)

                form.colonist.errors.append(
                    "Something went wrong submitting your registation. This usually means your colonist username or"
                    " email is not unique. Change them and if"
                    " the problem persists ask in the discord"
                )
                print(form.errors)
            else:
                send_webhook_message(user)
                flash("Registration Complete!")
                flask.session["user_info"] = flask.session["register_info"]
                flask.session.pop("register_info")
                flask.session.pop("registration_key")
                return flask.redirect("/registration/view")

        return flask.render_template(
            "register.html",
            form=form,
            discord_username=flask.session["register_info"]["username"]
            + "#"
            + flask.session["register_info"]["discriminator"],
        )
    return flask.abort(403)


def send_webhook_message(user: User):
    requests.post(
        flask.current_app.config.get("DISCORD_WEBHOOK_URL"),
        json={
            "content": f"""\
User <@{user.user_id}> ({user.username}) just registered on the website.
```diff
+ Colonist:                {user.colonist}
+ Country:                 {user.country}
+ Needs help with discord: {user.use_discord}
+ Special Accomodations:   {str(user.assistance)[:100]}
+ Referer:                 {user.referer}
```
See <https://catancommunity.org/stats/new-users> for mode details
        """,
            "username": user.username,
        },
    )


def is_registered(internal_user_id):
    return User.query.get(internal_user_id) is not None


@reg.route("/export_users")
def export_users():
    from app import is_admin

    if not is_admin():
        return flask.redirect("/403")
    data = io.StringIO()
    writer = csv.writer(data)
    users = User.query.all()
    column_names = [col.key for col in inspect(User).attrs]
    writer.writerow(column_names)
    for user_obj in users:
        writer.writerow([getattr(user_obj, col) for col in column_names])
    print(flask.request.path)
    response = make_response(data.getvalue())
    data.close()
    cd = "attachment; filename=AllUsers.csv"
    response.headers["Content-Disposition"] = cd
    response.mimetype = "text/csv"
    return response


@reg.route("/pre_update")
def pre_update_registration():
    if flask.session.get("user_info"):
        id = int(flask.session["user_info"]["id"])
        if is_registered(id):
            flask.session["update_key"] = id
            return flask.redirect(f"update/{id}")
    return flask.redirect("/")


@reg.route("/update/<int:user_id>", methods=["GET", "POST"])
def update_registration(user_id):
    if flask.session.get("update_key") == user_id:
        user = User.query.filter(User.user_id == user_id).first()

        if flask.request.method == "POST":
            form = RegistrationForm(flask.request.form)
        else:
            form = RegistrationForm(obj=user)
            form.server.data = "yes"

        if flask.request.method == "POST" and form.validate():
            user.update_auxiliary_fields(form)
            flask.session.pop("update_key")
            return flask.redirect("/registration/view/success")
        return flask.render_template(
            "register.html", form=form, discord_username=user.username
        )
    return flask.redirect("/")


@reg.route("/view", defaults={"success": None})
@reg.route("/view/<success>")
def view_registration(success):
    user_info = flask.session.get("user_info")
    if user_info:
        id = user_info["id"]
        if is_registered(id):
            user = User.query.get(id)
            updated = False
            if success == "success":
                updated = True
            return flask.render_template(
                "update_registration.html", user=user, view_only=True, success=updated
            )
    return flask.redirect("/")


@reg.route("/api/colonist_name", methods=["POST"])
@global_cache.csrf.exempt
def get_colonist_names():
    # float('nan') is guaranteed to not be equal to anything
    if flask.request.headers.get(
        "X-Authorization", float("nan")
    ) != flask.current_app.config.get("AUTHENTICATION_KEY"):
        return flask.abort(403)

    print("getting data")
    data = flask.request.json
    assert isinstance(data, list)
    for i in data:
        assert isinstance(i, int)

    registrations = User.query.filter(User.user_id.in_(data))
    colonist_names = {
        i.user_id: {
            "colonist_name": i.colonist,
            "expansions": {"c&k": i.ck, "seafarers": i.sf, "c&k+seafarers": i.cksf},
        }
        for i in registrations
    }

    print("\n".join(i.statement for i in flask_sqlalchemy.get_debug_queries()))

    return flask.jsonify(colonist_names)

templates/include/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Catan Community</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Rubik&display=swap" rel="stylesheet">
    <link rel="icon" href="{{ url_for('static', filename='smallicon.png') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='generated/style.css') }}">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block extra_styles %}
    {% endblock %}
</head>
<body>
{% block page_body %}
    <div class="space-above-footer">
        {% block nav %}
            <nav class="narrow-screen-only">
                <a id="dropdown-toggle">
                    Menu
                </a>
                <div class="spacer"></div>
                {% if session.user_info %}
                    <a href="{{ url_for('profile.view_profile', player_id=session.user_info.id) }}">
                        {{ session.user_info.username }}
                    </a>
                    <a href="{{ url_for('auth.logout') }}">
                        Logout
                    </a>
                {% else %}
                    <a href="{{ url_for('auth.login') }}">Login</a>
                {% endif %}
            </nav>
            <nav class="wide-screen-only">
                {% with nav=cms_nav() %}
                    {% for page in nav %}
                        {% if page.subpages %}
                            <div class="dropdown-button">
                        {% endif %}
                    <a href="{{ page.get_absolute_url() }}">
                        {{ page.nav_title }}
                    </a>
                    {% if page.subpages %}
                        <div class="dropdown-content">
                            {% with nav=page.subpages %}
                                {% include 'cms/example_templates/nav.html' %}
                            {% endwith %}
                        </div>
                        </div>
                    {% endif %}
                    {% endfor %}
                {% endwith %}
                <div class="spacer"></div>
                {% if session.user_info %}
                    {% if is_admin() %}
                        <div class="dropdown-button">
                            <a>
                                Admin tools
                            </a>
                            <div class="dropdown-content">
                                <ul>
                                    <li>
                                        <a href="{{ url_for('simple_flask_cms.editor_home') }}">
                                            CMS
                                        </a>
                                    </li>
                                    <li>
                                        <a href="{{ url_for('reg.export_users') }}" target="_blank">
                                            Export Users
                                        </a>
                                    </li>
                                    <li>
                                        <a href="{{ url_for('stats.get_stats') }}">
                                            Statistics
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    {% endif %}
                    <a href="{{ url_for('reg.view_registration') }}">
                        Registration
                    </a>
                    <a href="{{ url_for('profile.view_profile', player_id=session.user_info.id) }}">
                        {{ session.user_info.username }}
                    </a>
                    <a href="{{ url_for('auth.logout') }}">
                        Logout
                    </a>
                {% else %}
                    <a href="{{ url_for('auth.login') }}">Login</a>
                {% endif %}
            </nav>

            <div class="nav-sidebar hidden">
                <ul>
                    {% with nav=cms_nav() %}
                        {% for page in nav %}
                            <li>
                                <a href="{{ page.get_absolute_url() }}">
                                    {{ page.nav_title }}
                                </a>
                                {% if page.subpages %}
                                    {% with nav=page.subpages %}
                                        {% include 'cms/example_templates/nav.html' %}
                                    {% endwith %}
                                {% endif %}
                            </li>
                        {% endfor %}
                    {% endwith %}
                    {% if is_admin() %}
                        <li>
                            <a>
                                Admin tools
                            </a>
                            <ul>
                                <li>
                                    <a href="{{ url_for('simple_flask_cms.editor_home') }}">
                                        CMS
                                    </a>
                                </li>
                                <li>
                                    <a href="{{ url_for('reg.export_users') }}" target="_blank">
                                        Export Users
                                    </a>
                                </li>
                                <li>
                                    <a href="{{ url_for('stats.get_stats') }}">
                                        Statistics
                                    </a>
                                </li>
                            </ul>
                        </li>
                    {% endif %}
                    <li>
                        <a href="{{ url_for('reg.view_registration') }}">
                            Registration
                        </a>
                    </li>
                </ul>
            </div>
        {% endblock %}
        {% block cover_image %}

            <img class="cover-image" src="{{ url_for('static', filename='banner.svg') }}">
        {% endblock %}
        {% block page_content %}
        {% endblock %}

    </div>
    {% block page_footer %}
        <div class="clear"></div>
        <div class="footer">
            <a href="https://www.facebook.com/Catan-Community-104295705401042">
                <img src="{{ url_for('static', filename='brands/face.svg') }}" alt="facebook">
            </a>
            <a href="{{ get_discord_invite() }}">
                <img src="{{ url_for('static', filename='brands/discord.svg') }}" alt="facebook">
            </a>
            <a href="https://www.instagram.com/catan_community/">
                <img src="{{ url_for('static', filename='brands/insta.svg') }}" alt="instagram">
            </a>
            <a href="https://twitter.com/Catan_Community">
                <img src="{{ url_for('static', filename='brands/twitt.svg') }}" alt="twitter">
            </a>
            <br>
            <p>
                We are not affiliated, associated, authorized, endorsed by, or in any way officially connected with
                Catan®, CATAN GmbH, Klaus Teuber, or any of its subsidiaries or affiliates. The name Catan, as well as
                related names, trademarks, emblems and images are registered trademarks of their respective owners.
            </p>

            <div>
                Website provided by <a href="https://mousetail.nl">mousetail</a>. &copy;️ {{ get_year() }}. All rights
                reserved.
            </div>
        </div>
    {% endblock %}
{% endblock %}
<script src="{{ url_for('static', filename='generated/script.js') }}"></script>
<script>if(!sessionStorage.getItem("_swa")&&document.referrer.indexOf(location.protocol+"//"+location.host)!== 0){fetch("https://counter.dev/track?"+new URLSearchParams({referrer:document.referrer,screen:screen.width+"x"+screen.height,user:"mousetail",utcoffset:1}))};sessionStorage.setItem("_swa","1");</script>
</body>
</html>

templates/include/stat_image.html
<svg viewBox="0 0 {{ stat_positions|length * 2 }} 25">

    {% for point in stat_positions %}
        {% if point.0 % 3 == 0 and point.0 != 0 %}
            <line stroke-width="0.128" stroke="#ddd"
                  x1="{{ point.0 * 2 }}"
                  x2="{{ point.0 * 2 }}"
                  y1="2.5"
                  y2="25"
            >
            </line>
            <text x="{{ point.0 * 2 }}" y="2" font-size="0.8"
                  text-anchor="middle"
            >
                {{ point.3.strftime('%Y-%m-%d') }}
            </text>
        {% endif %}
    {% endfor %}
    {% for k in range(size, 23 * 64 // scale, size) %}
        <line stroke-width="0.064" stroke="#ddd"
              x1="2.5"
              x2="{{ stat_positions | length * 2 }}"
              y1="{{ 25 - scale * k / 64 }}"
              y2="{{ 25 - scale * k / 64 }}"
        ></line>
        <text x="0.5" y="{{ 25 - scale * k / 64 }}" font-size="0.8" alignment-baseline="middle">
            {{ k }}
        </text>
    {% endfor %}

    <path
            stroke="black" stroke-width="0.3" fill="none"
            stroke-linejoin="round"
            d="
                M -10 200
{% for point in stat_positions %}
L {{ point.0 * 2 }} {{ 25 - scale * point.1 / 64 }}
{% endfor %}
"
    ></path>

</svg>

<h2>
    Raw Data
</h2>

<table style="column-count: 2">
    <tr>
        <th>Year</th>
        <th>Week</th>
        <th>Date</th>
        <th class="unset_width">{{ name }}</th>

        <th>Year</th>
        <th>Week</th>
        <th>Date</th>
        <th class="unset_width">{{ name }}</th>
    </tr>
    {% for week in stat_positions | pairs %}
        <tr>
            <td>
                {{ week.0.2.0 }}
            </td>
            <td>
                {{ week.0.2.1 }}
            </td>
            <td>
                {{ week.0.3.strftime('%Y-%m-%d') }}
            </td>
            <td class="unset_width">
                {{ week.0.2.2 }}
            </td>


            <td>
                {{ week.1.2.0 }}
            </td>
            <td>
                {{ week.1.2.1 }}
            </td>
            <td>
                {{ week.1.3.strftime('%Y-%m-%d') }}
            </td>
            <td class="unset_width">
                {{ week.1.2.2 }}
            </td>
        </tr>
    {% endfor %}
</table>