models/tournament.py
import flask
from sqlalchemy.sql import func

from util import global_cache


class Tournament(global_cache.sql_db.Model):
    tournament_id = global_cache.sql_db.Column(
        global_cache.sql_db.Integer, primary_key=True, nullable=False
    )
    short_name = global_cache.sql_db.Column(
        global_cache.sql_db.String(255), nullable=False
    )
    long_name = global_cache.sql_db.Column(
        global_cache.sql_db.String(255), nullable=False
    )
    description = global_cache.sql_db.Column(
        global_cache.sql_db.String(255), nullable=False
    )
    role_id = global_cache.sql_db.Column(global_cache.sql_db.Integer, nullable=True)
    game_mode = global_cache.sql_db.Column(
        global_cache.sql_db.String(32), nullable=True
    )
    vp_to_win = global_cache.sql_db.Column(
        global_cache.sql_db.Integer, nullable=False, default=10
    )

    players_per_team = global_cache.sql_db.Column(
        global_cache.sql_db.Integer, nullable=False, default=1
    )
    teams_per_table = global_cache.sql_db.Column(
        global_cache.sql_db.Integer, nullable=False, default=4
    )


class TournamentPlayer(global_cache.sql_db.Model):
    id = global_cache.sql_db.Column(
        global_cache.sql_db.Integer, primary_key=True, nullable=False
    )
    tournament_id = global_cache.sql_db.Column(
        global_cache.sql_db.Integer,
        global_cache.sql_db.ForeignKey(Tournament.tournament_id),
    )
    discord_id = global_cache.sql_db.Column(global_cache.sql_db.Integer)
    discord_username = global_cache.sql_db.Column(
        global_cache.sql_db.String(128), nullable=False
    )
    colonist_username = global_cache.sql_db.Column(
        global_cache.sql_db.String(128), nullable=False
    )

    round_number = global_cache.sql_db.Column(
        global_cache.sql_db.Integer, nullable=False
    )

    table_number = global_cache.sql_db.Column(
        global_cache.sql_db.Integer, nullable=False
    )

blueprints/profile.py
import flask

import util.global_cache as global_cache
import util.leaderboard_util as leaderboard_util
from models.user import User

profile = flask.Blueprint(name="profile", import_name="profile", url_prefix="/profile")


class PlayerProfile(global_cache.sql_db.Model):
    id = global_cache.sql_db.Column(global_cache.sql_db.Integer, primary_key=True)
    discord_id = global_cache.sql_db.Column(
        global_cache.sql_db.String, index=True, unique=True
    )
    content = global_cache.sql_db.Column(global_cache.sql_db.LargeBinary)


# @global_cache.cache.memoize(args_to_ignore=['database'], timeout=60 * 60 * 24)
def get_bffs(database, player_id):
    return [
        {
            "name": player["player"][0]["display_name"],
            "games": player["count"],
            "id": int(player["player"][0]["discord_username"][2:-1]),
        }
        for player in database["matches"].aggregate(
            [
                {"$match": {"players": f"<@{player_id}>"}},
                {"$project": {"players": 1}},
                {"$unwind": "$players"},
                {"$group": {"_id": {"player": "$players"}, "count": {"$sum": 1}}},
                {"$sort": {"count": -1}},
                {"$skip": 1},
                {"$limit": 10},
                {
                    "$lookup": {
                        "from": "users",
                        "localField": "_id.player",
                        "foreignField": "discord_username",
                        "as": "player",
                    }
                },
            ]
        )
    ]


@profile.route("/<int:player_id>")
def view_profile(player_id):
    from app import is_admin

    player = global_cache.mongodb["users"].find_one(
        {"discord_username": f"<@{player_id}>"}
    )
    if player is None:
        return flask.render_template("fake_profile.html", player_id=player_id), 404

    rank = {
        league: tuple(
            leaderboard_util.get_user_rank(
                global_cache.mongodb,
                player["_id"],
                leaderboard_util.get_filter(i, league=league),
            )
            for i in (
                "month",
                "season",
                "all",
            )
        )
        for league in ("base", "ck")
    }

    profile_content = PlayerProfile.query.filter_by(discord_id=player_id).first()
    if profile_content is not None:
        profile_content = profile_content.content.decode("utf-8")

    if str(player_id) == flask.session.get("user_info", {}).get("id"):
        is_you = True
    else:
        is_you = False

    tournaments = global_cache.mongodb["user_lp"].find(
        {"type": "tourney", "user": player["_id"]}
    )

    if is_admin():
        user_model = User.query.filter_by(user_id=player_id).first()
        if user_model is not None:
            user = user_model.__dict__
        else:
            user = None
    else:
        user = None

    return flask.render_template(
        "profile.html",
        player=player,
        rank=rank,
        profile_content=profile_content,
        is_you=is_you,
        tournaments=tournaments,
        bffs=get_bffs(global_cache.mongodb, player_id),
        registation=user,
    )


@profile.route("/edit", methods=["GET", "POST"])
def edit_profile():
    discord_id = flask.session.get("user_info", {}).get("id")
    if discord_id is None:
        flask.abort(403)

    mongodb_user = (
        global_cache.mongodb["users"].find_one({"discord_username": f"<@{discord_id}>"})
        or {}
    )
    is_donator = mongodb_user.get("is_donator") or mongodb_user.get("is_admin")
    if is_donator:
        max_length = 1200
    else:
        max_length = 300

    user_profile = PlayerProfile.query.filter_by(discord_id=discord_id).first()
    if flask.request.method == "POST":
        if user_profile is None:
            user_profile = PlayerProfile(discord_id=str(discord_id), content=b"")
            global_cache.sql_db.session.add(user_profile)

        if len(flask.request.form["profile_content"]) > max_length:
            content = flask.request.form["profile_content"][:max_length]
        else:
            content = flask.request.form["profile_content"]

        user_profile.content = content.encode("utf-8")
        global_cache.sql_db.session.commit()

    return flask.render_template(
        "edit_profile.html",
        content=(user_profile and user_profile.content.decode("utf-8")) or "",
        max_length=max_length,
        player_id=int(discord_id),
    )

blueprints/registration.py
import csv
import io
import traceback

import flask
import flask_sqlalchemy
import requests
from flask import Blueprint
from flask.helpers import flash, make_response
from sqlalchemy import exc, inspect
from wtforms import (
    BooleanField,
    Form,
    RadioField,
    StringField,
    ValidationError,
    validators,
)

import util.global_cache as global_cache
from models.user import User

reg = Blueprint("reg", __name__, url_prefix="/registration")


class RegistrationForm(Form):
    server = RadioField(choices=["yes", "no"])
    colonist = StringField(
        validators=[validators.Length(min=3, max=12), validators.InputRequired()]
    )
    country = StringField(
        validators=[validators.Length(min=3, max=80), validators.Optional()]
    )
    email = StringField(
        validators=[
            validators.Length(min=5, max=120),
            validators.Email(),
            validators.Optional(),
        ]
    )
    use_discord = RadioField(choices=["please-help", "no-help"])
    assistance = StringField(
        validators=[validators.Length(min=0, max=500), validators.Optional()]
    )
    ck = BooleanField()
    ck_5_6 = BooleanField()
    sf = BooleanField()
    sf_5_6 = BooleanField()
    cksf = BooleanField()
    cksf_5_6 = BooleanField()
    base_5_6 = BooleanField()
    base_7_8 = BooleanField()

    def validate_server(form, field):
        if field.data != "yes":
            raise ValidationError("You must join the discord to participate")


@reg.before_app_first_request
def setup_db():
    import app

    global_cache.sql_db.init_app(app.app)
    global_cache.sql_db.create_all()


@reg.route("/pre_register")
def pre_register():
    if flask.session.get("register_info"):
        id = int(flask.session["register_info"]["id"])
        if not is_registered(id):
            flask.session["registration_key"] = id
            return flask.redirect(flask.url_for("reg.register", user_id=id))
    return flask.redirect("/")


@reg.route("/register/<int:user_id>", methods=["GET", "POST"])
def register(user_id):
    if flask.session.get("registration_key") == user_id:
        form = RegistrationForm(flask.request.form)
        if (
            flask.request.method == "POST"
            and form.validate()
            and not is_registered(user_id)
        ):
            (res,) = global_cache.sql_db.session.query(
                User.query.filter(User.user_id == user_id).exists()
            ).first()
            if res:
                return update_registration(user_id)

            user = User(
                user_id=user_id,
                username=flask.session["register_info"]["username"]
                + "#"
                + flask.session["register_info"]["discriminator"],
            )
            global_cache.sql_db.session.add(user)
            try:
                user.update_auxiliary_fields(form)
            except exc.SQLAlchemyError:
                traceback.print_exc()
                print("form.errors=", form.errors)

                form.colonist.errors.append(
                    "Something went wrong submitting your registation. This usually means your colonist username or"
                    " email is not unique. Change them and if"
                    " the problem persists ask in the discord"
                )
                print(form.errors)
            else:
                send_webhook_message(user)
                flash("Registration Complete!")
                flask.session["user_info"] = flask.session["register_info"]
                flask.session.pop("register_info")
                flask.session.pop("registration_key")
                return flask.redirect("/registration/view")

        return flask.render_template(
            "register.html",
            form=form,
            discord_username=flask.session["register_info"]["username"]
            + "#"
            + flask.session["register_info"]["discriminator"],
        )
    return flask.abort(403)


def send_webhook_message(user: User):
    requests.post(
        flask.current_app.config.get("DISCORD_WEBHOOK_URL"),
        json={
            "content": f"""\
User <@{user.user_id}> ({user.username}) just registered on the website.
```diff
+ Colonist:                {user.colonist}
+ Country:                 {user.country}
+ Needs help with discord: {user.use_discord}
+ Special Accomodations:   {str(user.assistance)[:100]}
+ Referer:                 {user.referer}
```
See <https://catancommunity.org/stats/new-users> for mode details
        """,
            "username": user.username,
        },
    )


def is_registered(internal_user_id):
    return User.query.get(internal_user_id) is not None


@reg.route("/export_users")
def export_users():
    from app import is_admin

    if not is_admin():
        return flask.redirect("/403")
    data = io.StringIO()
    writer = csv.writer(data)
    users = User.query.all()
    column_names = [col.key for col in inspect(User).attrs]
    writer.writerow(column_names)
    for user_obj in users:
        writer.writerow([getattr(user_obj, col) for col in column_names])
    print(flask.request.path)
    response = make_response(data.getvalue())
    data.close()
    cd = "attachment; filename=AllUsers.csv"
    response.headers["Content-Disposition"] = cd
    response.mimetype = "text/csv"
    return response


@reg.route("/pre_update")
def pre_update_registration():
    if flask.session.get("user_info"):
        id = int(flask.session["user_info"]["id"])
        if is_registered(id):
            flask.session["update_key"] = id
            return flask.redirect(f"update/{id}")
    return flask.redirect("/")


@reg.route("/update/<int:user_id>", methods=["GET", "POST"])
def update_registration(user_id):
    if flask.session.get("update_key") == user_id:
        user = User.query.filter(User.user_id == user_id).first()

        if flask.request.method == "POST":
            form = RegistrationForm(flask.request.form)
        else:
            form = RegistrationForm(obj=user)
            form.server.data = "yes"

        if flask.request.method == "POST" and form.validate():
            user.update_auxiliary_fields(form)
            flask.session.pop("update_key")
            return flask.redirect("/registration/view/success")
        return flask.render_template(
            "register.html", form=form, discord_username=user.username
        )
    return flask.redirect("/")


@reg.route("/view", defaults={"success": None})
@reg.route("/view/<success>")
def view_registration(success):
    user_info = flask.session.get("user_info")
    if user_info:
        id = user_info["id"]
        if is_registered(id):
            user = User.query.get(id)
            updated = False
            if success == "success":
                updated = True
            return flask.render_template(
                "update_registration.html", user=user, view_only=True, success=updated
            )
    return flask.redirect("/")


@reg.route("/api/colonist_name", methods=["POST"])
@global_cache.csrf.exempt
def get_colonist_names():
    # float('nan') is guaranteed to not be equal to anything
    if flask.request.headers.get(
        "X-Authorization", float("nan")
    ) != flask.current_app.config.get("AUTHENTICATION_KEY"):
        return flask.abort(403)

    print("getting data")
    data = flask.request.json
    assert isinstance(data, list)
    for i in data:
        assert isinstance(i, int)

    registrations = User.query.filter(User.user_id.in_(data))
    colonist_names = {
        i.user_id: {
            "colonist_name": i.colonist,
            "expansions": {"c&k": i.ck, "seafarers": i.sf, "c&k+seafarers": i.cksf},
        }
        for i in registrations
    }

    print("\n".join(i.statement for i in flask_sqlalchemy.get_debug_queries()))

    return flask.jsonify(colonist_names)

blueprints/stats.py
import datetime

import flask

import models.user as user
import util.global_cache as global_cache

stats = flask.Blueprint(name="stats", import_name="stats", url_prefix="/stats")


def compute_stats_for_category(db_table):
    weekly_stats = [
        (i["_id"]["year"], i["_id"]["week"], i["count"])
        for i in db_table.aggregate(
            [
                {
                    "$group": {
                        "_id": {
                            "week": {
                                "$isoWeek": {
                                    "$dateFromParts": {
                                        "year": {"$year": "$_id"},
                                        "month": {"$month": "$_id"},
                                        "day": {"$dayOfMonth": "$_id"},
                                    }
                                }
                            },
                            "year": {
                                "$isoWeekYear": {
                                    "$dateFromParts": {
                                        "year": {"$year": "$_id"},
                                        "month": {"$month": "$_id"},
                                        "day": {"$dayOfMonth": "$_id"},
                                    }
                                }
                            },
                        },
                        "count": {"$sum": 1},
                    }
                }
            ]
        )
    ]

    weekly_stats.sort()

    stat_positions = [
        (
            (i[0] - 2021) * 53 + i[1],
            i[2],
            i,
            datetime.datetime.fromisocalendar(i[0], i[1], 1),
        )
        for i in weekly_stats
    ]
    return stat_positions


@stats.route("/weekly_stats")
def get_stats():
    database = global_cache.mongodb
    game_stats = compute_stats_for_category(database["matches"])
    player_stats = compute_stats_for_category(database["users"])

    return flask.render_template(
        "stats.html", game_stats=game_stats, player_stats=player_stats
    )


@stats.route("/new-users/<sort>/<int:page>")
@stats.route("/new-users")
def newly_registered_users(sort="updated", page=0):
    sort_option = {
        "pk": user.User.user_id.desc(),
        "updated": user.User.registration_update_date.desc(),
        "created": user.User.registration_date.desc(),
    }.get(sort)

    users = user.User.query.order_by(sort_option).paginate(page, 35, False)

    return flask.render_template("new_users.html", users=users, sort=sort)

blueprints/tournaments.py
import flask
from models.tournament import Tournament, TournamentPlayer

tournaments = flask.Blueprint("tournaments", __name__, url_prefix="/tournaments")


@tournaments.route("/new", methods=["GET", "HEAD", "POST"])
def new_tournament():
    if flask.request.method == "POST":
        pass

    return flask.render_template("tournament_create.html", {})


@tournaments.route("/<int:tournament_id>")
def view_tournamnet(tournament_id):
    pass


@tournaments.route("/<int:tournament_id>/edit")
def edit_tournament(tournament_id):
    pass


@tournaments.route(
    "/<int:tournament_id>/update/<int:round>/<int:player>/<int:score>/<int:win>"
)
def update_score(tournament_id, round, player, score, win):
    pass


@tournaments.route("/<int:tournament_id>/reshuffle/<int:round>")
def update_round(tournament_id, round):
    pass


@tournaments.route("/<int:tournament_id>/set_public/<int:round>")
def set_public(tournament_id, round):
    pass

templates/edit_profile.html
{% extends 'include/base.html' %}
{% block cover_image %}
{% endblock %}
{% block page_content %}

    <h2>Edit public profile</h2>

    <div class="main-content">
        <p>If you want to edit your tournament registration please do so in <a
                href="{{ url_for('reg.view_registration') }}">registration</a></p>

        <p>
            Donators and contributors get 1000 characters and limited markdown support. Other players get 300
            characters.
        </p>
        <form method="post">

            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
            <textarea maxlength="{{ max_length }}" name="profile_content">{{ content }}</textarea>

            <button type="submit">
                Update
            </button>
            <a href="{{ url_for('profile.view_profile', player_id=player_id) }}">Back to profile</a>
        </form>
    </div>
{% endblock %}

templates/fake_profile.html
{% extends 'include/base.html' %}
{% block cover_image %}
{% endblock %}
{% block page_content %}
    <div class="main-content">
        <div class="profile-banner">
            <img src="/cms/images/fbotwebp.webp" class="profile-image" alt="Player Profile">
            <div class="profile-name">
                Player#{{ player_id }}
            </div>
            <div class="profile-role">
                Future Member
            </div>
        </div>

        <h2>Earn at least 1 LP to unlock your profile</h2>

        <div>Check out <a href="/cms/explanation/Bot-Commands">explanation</a> to learn how to quickly jump into a game</div>

        {% for league in ('base', 'ck') %}
            <div class="profile-blocks">
                <a class="profile-block" href="{{ url_for('leaderboard', period='month', league=league) }}">
                    <div>
                        ??? lp
                    </div>
                    <div class="big-number">
                        #???
                    </div>
                    <div>
                        for {{ league }} league this month
                    </div>
                </a>
                <a class="profile-block" href="{{ url_for('leaderboard', period='season', league=league) }}">
                    <div>
                        ??? lp
                    </div>
                    <div class="big-number">
                        #???
                    </div>
                    <div>
                        for {{ league }} league this season
                    </div>
                </a>
                <a class="profile-block" href="{{ url_for('leaderboard', period='all', league=league) }}">
                    <div>??? lp
                    </div>
                    <div class="big-number">
                        #???
                    </div>
                    <div>
                        for {{ league }} league over all time
                    </div>
                </a>
            </div>
        {% endfor %}

        <h2>About this player</h2>
        <p>
            Earn at least 1 LP to customize what is said here
        </p>
    

        <h2> Best Friends</h2>
        <p> Earn at least 1 LP to see who your best friends are</p>
        <table>
            <tr>
                <th>
                    Name
                </th>
                <th>
                    Games
                </th>
            </tr>
            {% for bf in range(10) %}
                <tr>
                    <td class="unset_width">
                        ???
                    </td>

                    <td> ???</td>
                </tr>
            {% endfor %}
        </table>

        <h2>
            Tournaments
        </h2>

        <p>If you earned LP via a tournament it may take a few days for the information to be updated</p>

        <table>
            <tr>
                <th>date</th>
                <th class="unset_width">Tournament Name</th>
                <th>Mode</th>
            </tr>
            {% for i in range(10) %}
                <tr>
                        <td>??? / ???</td>
                        <td class="unset_width"> ???</td>
                        <td> ???? </td>
                    </tr>
                
            {% endfor %}
        </table>
    </div>
{% endblock %}

templates/home.html
{% extends 'include/base.html' %}

{% block page_content %}
    <h1>
        <img src="{{ url_for('static', filename='smallicon.png') }}" width="64">
        Catan Community
    </h1>
    <div class="tagline">{{ cms_fragment('home_tagline') | safe }}</div>
    <div class="main-content">
        {{ cms_fragment('home_top_section') | safe }}
    </div>
    <div class="two-columns">
        <div>
            {{ cms_fragment('home_left_column') | safe }}
            <a class="button" href="{{ get_discord_invite() }}">
                Join server
            </a>
        </div>
        <div>
            {{ cms_fragment('home_right_column') | safe }}

            <a class="button" href="{{ get_discord_invite() }}">
                Sign Up!
            </a>
        </div>


    </div>
    <div class="main-content">
        {{ cms_fragment('home_bottom_area') | safe }}

        <h2>Testimonials</h2>

        <div class="quote">
            {{ cms_fragment('home_quote_1') | safe }}
        </div>

        <div class="quote">

            {{ cms_fragment('home_quote_2') | safe }}

        <div class="quote">

            {{ cms_fragment('home_quote_3') | safe }}
        </div>
        <div class="quote">

            {{ cms_fragment('home_quote_4') | safe }}
        </div>
    </div>
{% endblock %}

templates/leaderboard.html
{% extends 'include/base.html' %}
{% block cover_image %}
{% endblock %}
{% block page_content %}
    <h1>Leaderboard {% if league %}{{ league }} league{% endif %} {{ date_formatted }}</h1>

    <div class="leaderboard-categories">
        {% for child in children %}
            <a href="{{ child.url }}">
                {{ child.name }}
            </a>
        {% endfor %}
    </div>

    <div class="main-content">
        <table class="leaderboard">
            <tr>
                <th>
                    Rank
                </th>
                <th class="unset_width">
                    Name
                </th>
                <th>
                    LP
                </th>
                <th>
                    Relative wins
                </th>
                <th>
                    Games
                </th>
            </tr>
            {% for player in leaderboard %}
                <tr>
                    <td>
                        {{ player[0] }}
                    </td>
                    <td class="unset_width">
                        {% if player[0] <= 10 %}
                            {% if  player.1.user_data.0.profile_picture_url %}
                                <img src="{{ player.1.user_data.0.profile_picture_url }}">
                            {% else %}
                                <img src="{{ url_for('static', filename='bot.webp') }}">
                            {% endif %}
                        {% endif %}
                        <a href="{{ url_for('profile.view_profile', player_id=player.1.player_id) }}">
                            {{ player[1].user_data.0.display_name }}
                        </a>
                    </td>
                    <td>
                        {{ '{:,}'.format(player[1].lp) }}
                    </td>
                    <td>
                        {{ '{:.3f}x'.format(player[1].normalized_wins / ((1, player[1].matches)|max)) }}
                    </td>
                    <td>
                        {{ player[1].matches }}
                    </td>
                </tr>
            {% endfor %}
        </table>
    </div>
{% endblock %}

templates/page.html
{% extends 'include/base.html' %}
{% block cover_image %}
{% endblock %}
{% block page_content %}
    <h1>{{ page.tile }}</h1>
    <div class="main-content">
        {{ page.html | safe }}


        {% if is_admin() %}
            <a href="{{ url_for('simple_flask_cms.editor', path=page.path) }}">
                Edit this page
            </a>
        {% endif %}
    </div>

{% endblock %}

templates/stats.html
{% extends 'include/base.html' %}
{% block cover_image %}
{% endblock %}
{% block page_content %}
    <h2>Games by week</h2>

    {% with stat_positions=game_stats,  scale=1, name="Games", size=200%}
        {% include 'include/stat_image.html' %}
    {% endwith %}
    <h2>New players by week</h2>


    {% with stat_positions=player_stats, scale=16, name="Players", size=10 %}
        {% include 'include/stat_image.html' %}
    {% endwith %}
{% endblock %}

templates/tournament_create.html
{% extends "include/base.html" %}
{% block page_content %}

<form method="POST">
    <button type="submit">Create Tournament</button>
</form>

{% endblock %}

templates/update_registration.html
{% extends 'include/base.html' %}
{% block cover_image %}
{% endblock %}
{% block page_content %}
<link rel="stylesheet" href="{{ url_for('static', filename='forms/validation.css') }}">


{% if success %}
<h1>Your Registration Information was updated successfully!</h1>
{% else %}
<h1>Your Registration Information</h1>
{% endif %}
<div class="main-content">


    <div class="success">
        <p>Your registation information is saved. You can edit it below if it's changed.</p>
        <p>While waiting for the tournament to start, <a href="/cms/explanation/Bot-Commands">play some practice
                games</a> to get started
            <a href="/cms/explanation/League-Points">Collecting some LP</a>. Those with the most LP from tournaments and
            match maker games can earn a spot in the special exclusive <a href="/cms/Tournaments/End-of-Month">Month
                finals</a> tournament.
        </p>
    </div>

    {% if view_only %}
    <form action="{{ url_for('reg.pre_update_registration') }}">
        {% else %}
        <form method="post">
            {% endif %}
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
            <fieldset {% if view_only %} readonly disabled {% endif %}>
                <label>
                    <h3>Discord Username:</h3>
                    <input readonly disabled
                        value="{{ session.user_info.username }}#{{ session.user_info.discriminator }}">
                </label>

                <label>
                    <h3>Colonist Username:</h3>
                    <input name="colonist" minlength="3" maxlength="12" value="{{ user.colonist }}" required>
                </label>

                <h3>Expansions Owned</h3>
                <div class="columns">
                    <div>
                        <p><label><input type="checkbox" name="ck" {% if user.ck %} checked {% endif %}>Cities &
                                Knights</label></p>
                        <p><label><input type="checkbox" name="ck_5_6" {% if user.ck_5_6 %} checked {% endif %}>Cities &
                                Knights 5-6 Player</label></p>
                        <p><label><input type="checkbox" name="sf" {% if user.sf %} checked {% endif
                                    %}>Seafarers</label></p>
                    </div>
                    <div>
                        <p><label><input type="checkbox" name="sf_5_6" {% if user.sf_5_6 %} checked {% endif
                                    %}>Seafarers 5-6 Player</label></p>
                        <p><label><input type="checkbox" name="cksf" {% if user.cksf %} checked {% endif %}>Cities &
                                Knights + Seafarers</label></p>
                        <p><label><input type="checkbox" name="cksf_5_6" {% if user.cksf_5_6 %} checked {% endif
                                    %}>Cities & Knights + Seafarers 5-6 Player</label></p>
                    </div>
                    <div>
                        <p><label><input type="checkbox" name="base_5_6" {% if user.base_5_6 %} checked {% endif %}>Base
                                5-6 Player</label></p>
                        <p><label><input type="checkbox" name="base_7_8" {% if user.base_7_8 %} checked {% endif %}>Base
                                7-8 Player</label></p>
                    </div>
                </div>

                <label>
                    <h3>Home Country:</h3>
                    <input name="country" maxlength="80" value="{{ user.country }}">
                </label>

                <label>
                    <h3>Email:</h3>
                    <input name="email" maxlength="120" type="email" value="{{ user.email or '' }}">
                </label>

                <h3>Discord Proficiency:</h3>
                {% if user.use_discord == "please-help" %}
                <p><label><input type="radio" name="use_discord" value="please-help" checked required>I could use some
                        help</label></p>
                <p><label><input type="radio" name="use_discord" value="no-help" required>I can manage</label></p>
                {% else %}
                <p><label><input type="radio" name="use_discord" value="please-help" required>I could use some
                        help</label></p>
                <p><label><input type="radio" name="use_discord" value="no-help" checked required>I can manage</label>
                </p>
                {% endif %}

                <label>
                    <h3>Special Needs/Accommodations:</h3>
                    <input name="assistance" maxlength="500" type="text" value="{{ user.assistance }}">
                </label>

            </fieldset>
            {% if view_only %}
            <button type="submit">Edit Registration</button>
            {% else %}
            <button type="submit">Update Registration</button>
            {% endif %}
        </form>
</div>
{% endblock %}